arm: 

 joint_names: [lbr_iiwa_joint_1, lbr_iiwa_joint_2, lbr_iiwa_joint_3, lbr_iiwa_joint_4, lbr_iiwa_joint_5,lbr_iiwa_joint_6, lbr_iiwa_joint_7]
 base_link: "lbr_iiwa_link_0"
 tip_link: "lbr_iiwa_link_7"
 ik_number_attemps: 10
 ik_attemp_timeout: 100
