<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="mast_height" value="0.708"/>
  <xacro:property name="mast_width" value="0.04"/>

  <xacro:macro name="mast" params="parent_link name *origin">
    <joint name="${name}_fixed_base_joint" type="fixed">
       <insert_block name="origin"/>
       <child link="${name}_link" />
       <parent link="${parent_link}"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${0.5 * mast_height}" rpy="0 0 0" />
        <geometry>
          <box size="${mast_width} ${mast_width} ${mast_height}"/>
        </geometry>
        <material name="Light Grey"/>
      </visual>

      <collision>
        <origin xyz="0 0 ${0.5 * mast_height}" rpy="0 0 0" />
        <geometry>
          <box size="${mast_width} ${mast_width} ${mast_height}"/>
        </geometry>
        <material name="Light Grey"/>
      </collision>

      <inertial>
        <!--estimated from geometry and density of alumium-->
        <origin xyz="0 0 ${0.5 * mast_height}" rpy="0 0 0" />
        <mass value="6.3" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
        </inertial>
    </link>
    
    <joint name="${name}_joint_mount" type="fixed">
       <origin xyz="0.0 0.0 ${mast_height}" rpy="0 0 0"/>
       <parent link="${name}_link"/>
       <child link="${name}_link_mount" />
    </joint>

    <link name="${name}_link_mount"/>

    <gazebo reference="${name}_link">
      <selfCollide>true</selfCollide>
      <material>Gazebo/Grey</material>
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
    </gazebo>

  </xacro:macro>

</robot>
